function laguerreFunc = makeLaguerreFuncDerivs ...
    (laguerrePol,laguerreFunc,laguerreGQNodes)
    
    % First 4 derivatives...
    for k=1:size(laguerreGQNodes,1)
        for i=1:size(laguerrePol,3)
            
            laguerreFunc(2,k,i) = exp(-laguerreGQNodes(k,1)/2) *...
                ( laguerrePol(2,k,i) - (1/2)*laguerrePol(1,k,i) );
            
            laguerreFunc(3,k,i) = exp(-laguerreGQNodes(k,1)/2) *...
                ( laguerrePol(3,k,i) - laguerrePol(2,k,i) + ...
                (1/4)*laguerrePol(1,k,i) );
            
            laguerreFunc(4,k,i) = exp(-laguerreGQNodes(k,1)/2) *...
                ( laguerrePol(4,k,i) - (3/2)*laguerrePol(3,k,i) + ...
                (3/4)*laguerrePol(2,k,i) - (1/8)*laguerrePol(1,k,i) );
            
            laguerreFunc(5,k,i) = exp(-laguerreGQNodes(k,1)/2) *...
                ( laguerrePol(5,k,i) - 2*laguerrePol(4,k,i) + ...
                (3/2)*laguerrePol(3,k,i) - (1/2)*laguerrePol(2,k,i) + ...
                (1/16)*laguerrePol(1,k,i) );
            
        end
    end
    
end