function plotEigenValues(linearSol,parabolicSol,blasiusSol)

    figure;
    h1=scatter(linearSol.real,linearSol.imag,...
        50,...
        'ok',...
        'linewidth',2); hold on;
    h2=scatter(parabolicSol.real,parabolicSol.imag,...
        50,...
        'dr',...
        'linewidth',2); hold on;
    h3=scatter(blasiusSol.real,blasiusSol.imag,...
        50,...
        'sb',...
        'linewidth',2); hold on;
    
    % Formatting...
    box on; grid on;
    xlabel('$Re(c)$',...
        'FontSize',16,...
        'interpreter','latex');
    ylabel('$Im(c)$',...
        'FontSize',16,...
        'interpreter','latex');
    set(gcf, 'Position',...
        [100, 100, 500, 400]);
    xL = xlim;
    yL = ylim;
    line([0 0], yL,'color','k','linestyle','--');  %x-axis
    line(xL, [0 0],'color','k','linestyle','--');  %y-axis
    legend([h1,h2,h3],...
        'Linear Base Profile','Parabolic Base Profile',...
        'Blasius Base Profile');

end