function plotChannelFlowBaseProfiles(yChannel,profile1,profile2,profile3)

    figure;
    plot( profile1,yChannel,...
        '-ok',...
        'linewidth',2,...
        'markerindices',1:2:size(yChannel,1) ); hold on;
    plot( profile2,yChannel,...
        '-dr',...
        'linewidth',2,...
        'markerindices',1:2:size(yChannel,1) ); hold on;
    plot( profile3,yChannel,...
        '-sb',...
        'linewidth',2,...
        'markerindices',1:2:size(yChannel,1) ); hold off;
    xlabel( '$\overline{u}(y)$',...
        'fontsize',16,...
        'interpreter','latex' );
    ylabel( '$y$',...
        'fontsize',16,...
        'interpreter','latex' ); 
    grid on; box on;
    legend('$\overline{u}_1(y)$','$\overline{u}_2(y)$',...
        '$\overline{u}_3(y)$');

end