function plotChannelFlowBaseProfiles(nodes)

    if(size(nodes,1)==1); nodes=transpose(nodes); end
    profile1 = makeChannelBaseFlow (nodes, 1);
    profile2 = makeChannelBaseFlow (nodes, 2);
    profile3 = makeChannelBaseFlow (nodes, 3);
    
    figure;
    
    subplot(1,2,1);
    plot( profile1(:,1),nodes,...
        '-ok',...
        'linewidth',2,...
         'markerindices',1:10:size(nodes,1) ); hold on;
    plot( profile2(:,1),nodes,...
        '-dr',...
        'linewidth',2,...
        'markerindices',1:10:size(nodes,1) ); hold on;
    plot( profile3(:,1),nodes,...
        '-sb',...
        'linewidth',2,...
        'markerindices',1:10:size(nodes,1) ); hold off;
    xlabel( '$U(y)$',...
        'fontsize',16,...
        'interpreter','latex' );
    ylabel( '$y$',...
        'fontsize',16,...
        'interpreter','latex' ); 
    grid on; box on;
    legend('U_1(y)','U_2(y)','U_3(y)');
    
    subplot(1,2,2);
    plot( profile1(:,2),nodes,...
        '-ok',...
        'linewidth',2,...
         'markerindices',1:10:size(nodes,1) ); hold on;
    plot( profile2(:,2),nodes,...
        '-dr',...
        'linewidth',2,...
        'markerindices',1:10:size(nodes,1) ); hold on;
    plot( profile3(:,2),nodes,...
        '-sb',...
        'linewidth',2,...
        'markerindices',1:10:size(nodes,1) ); hold off;
    xlabel( '$U"(y)$',...
        'fontsize',16,...
        'interpreter','latex' );
    ylabel( '$y$',...
        'fontsize',16,...
        'interpreter','latex' ); 
    grid on; box on;

end